name: SimpleExample

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@v3
    # Build
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: echo "Hello world"
# This is a simple workflow for a python app