name: SimpleExample

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@v3
    # Build
    - uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Run custom action
    - uses: pmorphic/udacity-first-greetings-action@main
# This is a simple workflow for a python app